### ISSUE TITLE
The requested route [/routes] has not been mapped in Spark

### ISSUE THREAD

**Issue by bonjourmauko** [conveyal/gtfs-api#20]
I'm trying to use ```gtfs-api``` following the ```README```.

I've added a GTFS file under ```data/tisseo_gtfs.zip```, and tried to navigate to ```http://localhost:4567/routes?feed=tisseo-gtfs-zip```.

In the browser, I get ```404 Not found```.

In the stdout, I get ```The requested route [/routes] has not been mapped in Spark```.

Here's my ```application.conf``` file's content:

```
# This is the main configuration file for gtfs-api component.

# Offline path for gtfs feeds
application.data=data/

# The S3 buckets configured below must be accessible using the AWS credentials available on your machine.
# See http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html for information
# on how to provide these credentials to Transport Analyst using environment variables or a properties file.

# The S3 bucket in which to get GTFS feeds
s3.feeds-bucket=<BUCKET>
s3.bucket-folder=gtfs
s3.work-offline=true
```

cc @l-vincent-l

**Comment by abyrd** [comment]
Hello, we have not been using this repo since around 21 November 2017. At that time we integrated the API definition code directly into gtfs-lib with this commit: https://github.com/conveyal/gtfs-lib/commit/c69f771a0327a01c8452d067435a33823df1aeff#diff-c7cbcf7bd00fb9f83c0f4ae2d1b307da

`datatools-server` now depends on the `sql-editor` branch of `gtfs-lib`, which directly contains the API definition. Note that `gtfs-lib` does not provide an HTTP server layer over the API. The HTTP server layer is supplied by whatever project imports `gtfs-lib` (in this case `datatools-server`).

I'll add a note to the README explaining the situation.
